### PR TITLE
Get restrictions information

### PR DESCRIPTION
**Pull request by bonniegee**
Adds the following functions to `helpers.py`:

* get_preferred_rights()
	* First checks for a rights statement, then checks for a restrictions apply boolean, and then checks note content
	* Question: When we're checking note content, we're going to iterate up an archival object's ancestors; do we want to do the same for the restrictions_apply boolean?
	* Question: If an archival object has restrictions_apply as True, but does not have a conditions governing access note at that level, do we want to iterate up ancestors until we find a note?
	* This function doesn't really return anything; I imagine we'll want to take an approach like `get_preferred_format` and return a tuple. Does that sound like the right direction?
* get_rights_notes()
	* This iterates up conditions governing access notes, looking for a restriction. Only checks conditions governing access notes which are published.
	* Question: to confirm, we're checking collection level note text?
	* Question: For determing whether a conditions governing access note indicates a restriction, it seems that there are (at least) two approaches:
		1. Search the note text for specific words the indicate a restriction, such as "closed" and restricted.
		2. Use the "text_in_note" function to exclude conditions governing access notes that we know do *not* indicate a restriction.
	* Question: I am unsure how we'll want to handle this conditions governing access note: "Access copy currently unavailable. Please contact a RAC archivist for further assistance." Should conditional be used in this case, or should the relevant restriction be handled by the preferred delivery format method? (I should note I'm pretty sure these notes only appear for AV items.)
	* We'll want to change what this returns, but it depends on what `get_preferred_rights` will need

Addresses #19

### CODE REVIEW

**Comment by helrond** [comment]
So I think in general we need to return a restriction status ("closed", "open", "conditional") as well as restriction text which describes the restriction status. I am not sure makes sense to try and return these both out of the same method because it's possible that the restriction status might come from a rights statement and the restriction text might come from a note. Its also possible that these restrictions will come from two different levels altogether, i.e. a rights statement on a file-level object and a note on a series-level object. So I think I would suggest writing this as two separate methods, one which gets the status and the other which gets the text. It's a little less efficient, but I think it will be easier to understand and maintain.

>   * Question: When we're checking note content, we're going to iterate up an archival object's ancestors; do we want to do the same for the restrictions_apply boolean?

As suggested above, I think it makes sense to iterate up the tree twice. For restrictions status, I think we'd want to look at `restrictions_apply`, `rights_statements` and then `access_restrict` notes (in that order) at each level of the tree we iterate up, until we find something. For the restriction text, we don't need to look at `restrictions_apply`, I don't think.

>   * Question: If an archival object has restrictions_apply as True, but does not have a conditions governing access note at that level, do we want to iterate up ancestors until we find a note?

See above - I think we need to decouple these two things, so functionally the answer is yes.

>   * This function doesn't really return anything; I imagine we'll want to take an approach like `get_preferred_format` and return a tuple. Does that sound like the right direction?

See above. This method can either call two other methods and return a tuple, or we can just have two methods that get called. Personally I think I'd prefer the latter.

>   * Question: to confirm, we're checking collection level note text?

Yup.

>   * Question: For determing whether a conditions governing access note indicates a restriction, it seems that there are (at least) two approaches:
>     
>     1. Search the note text for specific words the indicate a restriction, such as "closed" and restricted.
>     2. Use the "text_in_note" function to exclude conditions governing access notes that we know do _not_ indicate a restriction.

I think we'll want to use `text_in_note` twice to look for language indicating restrictions, language indicating no restrictions, and then everything that doesn't fall into those buckets is `conditional`. I can start a conversation with Processing to figure out if that's going to work.

>   * Question: I am unsure how we'll want to handle this conditions governing access note: "Access copy currently unavailable. Please contact a RAC archivist for further assistance." Should conditional be used in this case, or should the relevant restriction be handled by the preferred delivery format method? (I should note I'm pretty sure these notes only appear for AV items.)

I think that will probably end up in `conditional` which is fine because this would have to get routed in a different way than requests that can be fulfilled without additional intervention.

**Comment by helrond** [comment]
Would love to get some other eyes on this logic. My sense is that there are things that could be improved/are not accounted for so any and all comments welcome!

Tagging @bonniegee in here since I can't explicitly ask for her review on this PR because she initiated it.

**Comment by p-galligan** [comment]
So, in my review of this, there seems to be a minor disconnect between the `get_rights_status` and `get_rights_text` in the note checking. You're checking if notes are public to get the text in `get_rights_text`, but you're not doing that for determining restrictions in `get_rights_status`. 

This could be a complete non-issue if we never have unpublished accessrestrict notes that will match the queries, but it could lead to some funky results if we do.

**Comment by helrond** [comment]
@p-galligan Good catch - that logic is specifically meant to account for some of the practices articulated [here](https://docs.rockarch.org/processing-manual/processing/#step-24---add-file-level-conditions-of-access-notes-for-restricted-material), specifically the creation of unpublished notes with administrative information about the restrictions. Because that information is not intended to be public, we wouldn't want to return that here. There shouldn't be an unpublished accessrestrict note WITHOUT a published accessrestrict note though...

**Comment by bonniegee** [comment]
I'm still looking through this, and it's possible we're not at this bridge yet, but I was wondering how we're handling items that have no restrictions information at all. `get_rights_info` returns `None, None` in this case. Do we want to do anything else with this information at the processing stage, or deal with the logic when determining whether an item should be delivered?

**Comment by helrond** [comment]
@bonniegee I think it's pretty unlikely that would happen, because it would mean that an object **and all of its parents**(including the resource record) are without either a rights statement or an accessrestrict note. However, it would be relatively easy to throw in a default value of `open` for `status` at the end of that function. I'm less concerned about `text` returning `None`, since we really only care about that if the object is restricted.

**Comment by p-galligan** [comment]
@bonniegee Correct me if I'm wrong, but we're assuming that items with no restrictions information at all are just open, correct? So we'd just need to default to open, instead of `None`, right?

`is_submittable` only needs texts on restricted materials right now.

**Comment by bonniegee** [comment]
I think assuming no restrictions info at all == open makes sense.

**Comment by bonniegee** [comment]
I'm not sure if this is important at this stage or if it's more for implementation, but the current CLOSED_TEXT and OPEN_TEXT values mean that conditions governing access notes that include the word "restricted" but not "closed" (e.g., "Restricted - confidential") are "conditional" with the current logic. Additionally, it looks like note content along the lines of "Access copy unavailable. Please contact an archivist" (for A/V) and "Retrieval time may exceed 24 hours" (for oversized material) are set to conditional, and will therefore be submitted to Aeon. I think this is desired behavior, but just wanted to flag it. 

Specific values of what we're looking for aside, this logic looks good.

Can the `inherit_restrictions` and `is_restricted` methods be removed from routines.py?

**Comment by helrond** [comment]
Thanks @bonniegee - I just had a conversation with Bob B. about this, and he also suggested using "restricted" rather than "closed".

And yes, I think that behavior for the AV notes is desired behavior.

Updates coming shortly.

**Comment by helrond** [comment]
OK @p-galligan and @bonniegee I've tried to address your comments in the commits above. Would appreciate another look from you both!

**Review by p-galligan — APPROVED** [review]
Looks good to me based on previous comments!

**Comment by bonniegee** [comment]
Looks good to me!

**Pull request merged**
