### PR TITLE
Update fixture fields

### PR DESCRIPTION
**Pull request by helrond**
@p-galligan @bonniegee this updates the fixture as per conversations (I think). Questions/clarifications welcome!

### CODE REVIEW

**Review by p-galligan — APPROVED** [review]
This is what I was envisioning after our conversations.

**Comment by helrond** [comment]
I guess it is also possible that we could have a more nested structure but I'm trying to keep it simple for now.

**Comment by bonniegee** [comment]
This mostly looks good to me, but I'd like more clarity for the `restrictions` field. Since it's not a boolean, what are the possible values--closed, conditional, open? And is `conditional` _only_ triggered when there's a PREMIS rights statement? The restricted boolean is pretty clear if it's set to True; when we're evaluating the note content, do we ever expect to be able to parse out whether a restriction "conditional"?

**Comment by helrond** [comment]
> when we're evaluating the note content, do we ever expect to be able to parse out whether a restriction "conditional"?

My hope is that we're able to identify a set of phrases which we can categorize as covering two of the three categories and then everything else falls into the third category. I.e. if we can cover `closed` and `open` then everything else is `conditional`. This will take some working with Bob B, but I think we're probably already part of the way there given the work Katie did earlier with restrictions notes.

**Review by bonniegee — APPROVED** [review]

**Pull request merged**
